
[[main]]
 name = "文章"
 pageRef = "/"
 weight = 10

[[main]]
 name = "系列"
 pageRef = "/pve"
 weight = 20

[[main]]
 name = "关于"
 pageRef = "/about"
 weight = 30

[[subnavigation]]
 name = "标签"
 pageRef = "tags"
 weight = 10
